/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Datos;

/**
 *
 * @author joela
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    //crear un objeto para conectarnos a la clase Datos
    private Datos misDatos;
    
    //crear un metodo publico
    public void setDatos(Datos misDatos)
    {
        this.misDatos = misDatos;
    }            
    
    //crear una variable para el perfil del usuario
    private int perfil;
    //metodo para trasladar el valor de la variable perfil
    public void setPerfil(int perfil)
    {
        this.perfil = perfil;
    }
    
    //declarar las variables usuario y clave
    public static String usuario, clave;
    //crear mis metodos para obtener la informacion
    public void setUsuario(String usuario)
    {
        this.usuario = usuario;
    }
    public void setClave(String clave)
    {
        this.clave = clave;
    }
    
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenuItem();
        mnuProductos = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuCambioClave = new javax.swing.JMenuItem();
        mnuCambioUsuario = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuSalir = new javax.swing.JMenuItem();
        mnuMovimientos = new javax.swing.JMenu();
        mnuNuevaFactura = new javax.swing.JMenuItem();
        mnuReporteFacturas = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        mnuSoporteTecnico = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Ventas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        contenedor.setBackground(new java.awt.Color(102, 102, 102));
        contenedor.setAutoscrolls(true);

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mnuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/library bookmarked.png"))); // NOI18N
        mnuArchivo.setText("Archivo");

        mnuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Clientes.png"))); // NOI18N
        mnuClientes.setText("Clientes");
        mnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientesActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuClientes);

        mnuProductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/applications.png"))); // NOI18N
        mnuProductos.setText("Productos");
        mnuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProductosActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuProductos);

        mnuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Vista_icons_09.png"))); // NOI18N
        mnuUsuarios.setText("Usuarios");
        mnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuariosActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuUsuarios);
        mnuArchivo.add(jSeparator1);

        mnuCambioClave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuCambioClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Vista_icons_08.png"))); // NOI18N
        mnuCambioClave.setText("Cambio de Clave");
        mnuCambioClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCambioClaveActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuCambioClave);

        mnuCambioUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuCambioUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CambiarUsuario.png"))); // NOI18N
        mnuCambioUsuario.setText("Cambio de Usuario");
        mnuCambioUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mnuCambioUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCambioUsuarioActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuCambioUsuario);
        mnuArchivo.add(jSeparator2);

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuSalir);

        jMenuBar1.add(mnuArchivo);

        mnuMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Movimientos.png"))); // NOI18N
        mnuMovimientos.setText("Movimientos");

        mnuNuevaFactura.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuNuevaFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nuevo.png"))); // NOI18N
        mnuNuevaFactura.setText("Nueva Factura");
        mnuNuevaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevaFacturaActionPerformed(evt);
            }
        });
        mnuMovimientos.add(mnuNuevaFactura);

        mnuReporteFacturas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuReporteFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reporte.png"))); // NOI18N
        mnuReporteFacturas.setText("Reporte Facturas");
        mnuReporteFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReporteFacturasActionPerformed(evt);
            }
        });
        mnuMovimientos.add(mnuReporteFacturas);

        jMenuBar1.add(mnuMovimientos);

        mnuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ayuda2.png"))); // NOI18N
        mnuAyuda.setText("Ayuda");

        mnuSoporteTecnico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuSoporteTecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Vista_icons_06.png"))); // NOI18N
        mnuSoporteTecnico.setText("Soporte Tècnico");
        mnuSoporteTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSoporteTecnicoActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnuSoporteTecnico);

        jMenuBar1.add(mnuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProductosActionPerformed
        // generar una instancia al formulario productos
        frmProductos misProductos = new frmProductos();            
        contenedor.add(misProductos);
        misProductos.show();
    }//GEN-LAST:event_mnuProductosActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        //misDatos.grabarTodo();
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed
        // generar una instancia al formulario clientes    
        frmClientes clien = new frmClientes();
        contenedor.add(clien);
        clien.show();
    }//GEN-LAST:event_mnuClientesActionPerformed

    private void mnuCambioUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCambioUsuarioActionPerformed
        // vamos a realizar el cambio de usuario
        this.setVisible(false); //ocultamos el formulario principal
        frmLogin login = new frmLogin();
        login.setDatos(misDatos);
        login.setLocationRelativeTo(null);//centramos el formulario
        login.setVisible(true); //mostramos el formulario de login
    }//GEN-LAST:event_mnuCambioUsuarioActionPerformed

    private void mnuNuevaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevaFacturaActionPerformed
        // mostramos el formulario nueva factura
        frmFactura factura = new  frmFactura();
        contenedor.add(factura);
        factura.show();
    }//GEN-LAST:event_mnuNuevaFacturaActionPerformed

    private void mnuReporteFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReporteFacturasActionPerformed
         // mostramos el formulario REPORTE DE FACTURAS
        frmReporte rfacturas = new frmReporte();
        contenedor.add(rfacturas);
        rfacturas.show();
    }//GEN-LAST:event_mnuReporteFacturasActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // cargar el perfil del usuario, para definir los permisos
        if(perfil == 2)
        {
            mnuClientes.setEnabled(false);
            mnuProductos.setEnabled(false);
            mnuUsuarios.setEnabled(false);
            mnuReporteFacturas.setEnabled(false);
        }
    }//GEN-LAST:event_formWindowOpened

    private void mnuCambioClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCambioClaveActionPerformed
        // generamos una instancia para conectarnos al formulario cambio de clave
        frmCambioClave cambioClave = new  frmCambioClave(this, rootPaneCheckingEnabled);
        //cambioClave.setClave(clave);
        //cambioClave.setUsuario(usuario);
        //cambioClave.setDatos(misDatos);
        cambioClave.setLocationRelativeTo(this);
        cambioClave.setVisible(rootPaneCheckingEnabled); 
    }//GEN-LAST:event_mnuCambioClaveActionPerformed

    private void mnuSoporteTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSoporteTecnicoActionPerformed
        // mostramos el formulario soporte tecnico
        frmSoporte soporte = new frmSoporte();
        contenedor.add(soporte);
        soporte.show();
    }//GEN-LAST:event_mnuSoporteTecnicoActionPerformed

    private void mnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuariosActionPerformed
        // generar una instancia al formulario usuarios
        frmUsuario misUsuarios = new frmUsuario();
        //misUsuarios.setDatos(misDatos);
        contenedor.add(misUsuarios);
        misUsuarios.show();
    }//GEN-LAST:event_mnuUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane contenedor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenuItem mnuCambioClave;
    private javax.swing.JMenuItem mnuCambioUsuario;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenu mnuMovimientos;
    private javax.swing.JMenuItem mnuNuevaFactura;
    private javax.swing.JMenuItem mnuProductos;
    private javax.swing.JMenuItem mnuReporteFacturas;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenuItem mnuSoporteTecnico;
    private javax.swing.JMenuItem mnuUsuarios;
    // End of variables declaration//GEN-END:variables
}
