/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;


import Clases.ConectarProductos;
import Clases.Producto;
import Clases.Utilerias;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joela
 */
public class frmProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmProductos
     */
    public frmProductos() {
        initComponents();
    }
    
    private Connection con;
    
    //modificar los parametros de la tabla
    private DefaultTableModel miTabla;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrimero = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        txtDescripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdProductos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbIVA = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNota = new javax.swing.JTextArea();
        btnBuscar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnPrimero2 = new javax.swing.JButton();
        btnAnterior2 = new javax.swing.JButton();
        btnSiguiente2 = new javax.swing.JButton();
        btnUltimo2 = new javax.swing.JButton();

        btnPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Primero.png"))); // NOI18N
        btnPrimero.setToolTipText("Va al primer registro");

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Anterior.png"))); // NOI18N
        btnAnterior.setToolTipText("Va al anterior registro");

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Siguiente.png"))); // NOI18N
        btnSiguiente.setToolTipText("Va al siguiente registro");

        btnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ultimo.png"))); // NOI18N
        btnUltimo.setToolTipText("Va al ultimo registro");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("PRODUCTOS");
        setAutoscrolls(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        txtDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Id Productos*:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Descripcion*:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Precio* :");

        txtIdProductos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("IVA*:");

        cmbIVA.setEditable(true);
        cmbIVA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "5%", "12%", "" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Notas* :");

        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblTabla);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("*Campos Obligatorios");

        txtNota.setColumns(20);
        txtNota.setRows(5);
        jScrollPane1.setViewportView(txtNota);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        btnBuscar.setToolTipText("Buscar registro");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        btnConsultar.setToolTipText("Consultar registro");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/applications.png"))); // NOI18N
        btnLimpiar.setToolTipText("Limpiar registro");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nuevo.png"))); // NOI18N
        btnNuevo.setToolTipText("Nuevo registro");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/library bookmarked.png"))); // NOI18N
        btnPDF.setToolTipText("PDF del registro");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        btnModificar.setToolTipText("Modificar registro");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Borrar2.png"))); // NOI18N
        btnEliminar.setToolTipText("Eliminar registro");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnPrimero2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Primero.png"))); // NOI18N
        btnPrimero2.setToolTipText("Va al primer registro");

        btnAnterior2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Anterior.png"))); // NOI18N
        btnAnterior2.setToolTipText("Va al anterior registro");

        btnSiguiente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Siguiente.png"))); // NOI18N
        btnSiguiente2.setToolTipText("Va al siguiente registro");

        btnUltimo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ultimo.png"))); // NOI18N
        btnUltimo2.setToolTipText("Va al ultimo registro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmbIVA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(txtDescripcion)
                                .addComponent(jScrollPane1))
                            .addComponent(txtIdProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(621, 621, 621))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnPrimero2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAnterior2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSiguiente2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUltimo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConsultar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPDF)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbIVA)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPDF)
                    .addComponent(btnConsultar)
                    .addComponent(btnNuevo)
                    .addComponent(btnBuscar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnPrimero2)
                    .addComponent(btnAnterior2)
                    .addComponent(btnSiguiente2)
                    .addComponent(btnUltimo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //crear un metodo para limpiar los cuadros de textos
    private void limpiar()
    {
        txtIdProductos.setText("");
        txtDescripcion.setText("");
        txtPrecio.setText("");
        txtNota.setText("");
        cmbIVA.setSelectedIndex(0); //posicion cero es la primera
    }
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        llenarTabla();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String id = JOptionPane.showInputDialog(rootPane,"Ingrese el Id del producto a buscar");

        if(id.equals(""))
        {
            return;
        }

        ConectarProductos con = new ConectarProductos();
        Producto producto = con.getProducto(id);
        if(producto == null)
        {
            JOptionPane.showMessageDialog(rootPane,"Producto no existe");
            txtIdProductos.setText("");
            txtIdProductos.grabFocus();
            con.cerrarConexion();
            return;
        }
        txtIdProductos.setText(producto.getIdProductos());
        txtDescripcion.setText(producto.getDescripcion());
        txtPrecio.setText(String.valueOf(producto.getPrecio()));        
        cmbIVA.setSelectedIndex(producto.getIVA());
        txtNota.setText(producto.getNota());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        //validaciones
        if(txtIdProductos.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar el Id del producto");
            txtIdProductos.grabFocus();
            return;
        }
        ConectarProductos con = new ConectarProductos();
        Producto producto = con.getProducto(txtIdProductos.getText());
        if(producto == null)
        {
            JOptionPane.showMessageDialog(rootPane,"Producto no existe");
            txtIdProductos.setText("");
            txtIdProductos.grabFocus();
            con.cerrarConexion();
            return;
        }
        txtDescripcion.setText(producto.getDescripcion());
        txtPrecio.setText(String.valueOf(producto.getPrecio()));        
        cmbIVA.setSelectedIndex(producto.getIVA());
        txtNota.setText(producto.getNota());
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        //validaciones
        if(txtIdProductos.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar el Id del producto");
            txtIdProductos.grabFocus();
            return;
        }
        ConectarProductos con = new ConectarProductos();
        Producto producto = con.getProducto(txtIdProductos.getText());
        if(producto != null)
        {
            JOptionPane.showMessageDialog(rootPane,"Usuario ya existe");
            txtIdProductos.setText("");
            txtIdProductos.grabFocus();
            con.cerrarConexion();
            return;
        }
        if(!validarCampos())
        {
            con.cerrarConexion();
            return;
        }
        producto = new Producto(txtIdProductos.getText(),
            txtDescripcion.getText(),
            Integer.parseInt(txtPrecio.getText()),  
            cmbIVA.getSelectedIndex(),
            txtNota.getText());

        if(con.insertarProducto(producto))
        {
            JOptionPane.showMessageDialog(rootPane,"Producto ingresado correctamente");
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"Producto no ingresado correctamente");
        }

        //limpiar los campos
        limpiar();
        con.cerrarConexion();
        llenarTabla();
    }//GEN-LAST:event_btnNuevoActionPerformed

    //metodo privado para validar campos
    private boolean validarCampos()
    {
        if(txtDescripcion.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar el nombre del producto","Descripcion", WIDTH);
            txtDescripcion.grabFocus();
            return false;
        }
        
        if(txtPrecio.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar el precio del producto","Precio", WIDTH);
            txtPrecio.grabFocus();
            return false;
        }
        
        //revisar que no se ingrese un valor distinto a un numero
        if (!Utilerias.esNumero(txtPrecio.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar un valor numerico", "Precio", WIDTH);
            txtPrecio.setText("");
            txtPrecio.grabFocus();
            return false;
        }

        //revisar que el valor no sea negativo
        int precio = Integer.parseInt(txtPrecio.getText());
        if (precio <= 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar un valor mayor a cero", "Precio", WIDTH);
            txtPrecio.setText("");
            txtPrecio.grabFocus();
            return false;
        }
        
        if(cmbIVA.getSelectedIndex() == 0)
        {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar el IVA","IVA", WIDTH);
            cmbIVA.grabFocus();
            return false;
        }
        
        if (txtNota.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar una Nota del producto", "Nota", WIDTH);
            txtNota.grabFocus();
            return false;
        }        
        return true;
    }
    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        //crear un archivo PDF con la informacion de la tabla usuario
        Document documento = new Document();
        try {
            PdfWriter.getInstance(documento, new FileOutputStream("Productos.pdf"));
            String texto = "Reporte de Productos";
            Paragraph parrafo = new Paragraph(texto);
            documento.open();
            documento.add(parrafo);
            ConectarProductos conectar = new ConectarProductos();
            ResultSet rs = conectar.getProductos();

            while(rs.next())
            {
                texto = "ID: " + rs.getString("Id_productos") + " - Descripcion: "
                + rs.getString("Descripcion") + " - Precio: "
                + rs.getString("Precio") + " - IVA: "
                + IVA(rs.getString("IVA") + " - Nota: "
                + rs.getString("Nota"));

                parrafo = new Paragraph(texto);
                documento.add(parrafo);
            }
            conectar.cerrarConexion();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmUsuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(frmUsuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            documento.close();
            JOptionPane.showMessageDialog(rootPane, "Reporte generado");
        }
    }//GEN-LAST:event_btnPDFActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //validaciones
        if(txtIdProductos.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar el Id del producto");
            txtIdProductos.grabFocus();
            return;
        }
        ConectarProductos con = new ConectarProductos();
        Producto producto = con.getProducto(txtIdProductos.getText());
        if(producto == null)
        {
            JOptionPane.showMessageDialog(rootPane,"Producto no existe");
            txtIdProductos.setText("");
            txtIdProductos.grabFocus();
            con.cerrarConexion();
            return;
        }
        producto = new Producto(txtIdProductos.getText(),
            txtDescripcion.getText(),
            Integer.parseInt(txtPrecio.getText()),
            cmbIVA.getSelectedIndex(),
            txtNota.getText());

        if(!validarCampos())
        {
            con.cerrarConexion();
            return;
        }

        if(con.UpdateProducto(producto))
        {
            JOptionPane.showMessageDialog(rootPane,"Producto actualizado correctamente");
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"Producto no actualizado correctamente");
        }
        con.cerrarConexion();
        llenarTabla();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int resp = JOptionPane.showConfirmDialog(rootPane, "Esta seguro de eliminar el producto");
        if(resp != 0)
        {
            return;
        }
        //validaciones
        if(txtIdProductos.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar el Id del producto");
            txtIdProductos.grabFocus();
            return;
        }
        ConectarProductos con = new ConectarProductos();
        Producto producto = con.getProducto(txtIdProductos.getText());
        if(producto == null)
        {
            JOptionPane.showMessageDialog(rootPane,"Producto no existe");
            txtIdProductos.setText("");
            txtIdProductos.grabFocus();
            con.cerrarConexion();
            return;
        }
        if(con.deleteProducto(producto))
        {
            JOptionPane.showMessageDialog(rootPane, "Producto eliminado correctamente");
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Producto no eliminado");
        }
        limpiar();
        con.cerrarConexion();
        llenarTabla();
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    //crear un metodo privado para mostrar los registros en la tabla
    private void llenarTabla()
    {
        //generamos una instancia a la clase conectar
        ConectarProductos conectar = new ConectarProductos();
        
        try {
            //creamos un arreglo para los titulos de la tabla
            String titulos[] = {"Id Producto", "Descripcion", "Precio", "IVA", "Nota"};
            miTabla = new DefaultTableModel(null, titulos);
            String registros[] = new String[5];
        
            ResultSet rs = conectar.getProductos();
            while(rs.next())
            {
                registros[0] = rs.getString("Id_productos");
                registros[1] = rs.getString("Descripcion");
                registros[2] = rs.getString("Precio");
                registros[3] = IVA(rs.getString("IVA")); 
                registros[4] = rs.getString("Nota");                 
                miTabla.addRow(registros);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblTabla.setModel(miTabla);
        conectar.cerrarConexion();
    }

    //metodo para definir el perfil
    private String IVA(String IdIVA)
    {
        switch(IdIVA)
        {
            case "0": return "0%";
            case "1": return "5%";
            case "2": return "12%";
            default: return "No es una seleccion valida";
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnAnterior2;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnPrimero2;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnSiguiente2;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JButton btnUltimo2;
    private javax.swing.JComboBox<String> cmbIVA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTabla;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIdProductos;
    private javax.swing.JTextArea txtNota;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

}
